version: '2.1'

services:
  postgresdb:
    restart: always
    image: postgres
    env_file:
      - docker-files/databases.environ
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cmsnet

  redishost:
    image: redis
    volumes:
      - 'redisdata:/data'
    networks:
      - cmsnet

  wsgiapp:
    restart: always
    build:
      context: .
      dockerfile: docker-files/wsgiapp.dockerfile
    image: {{ cookiecutter.project_slug }}
    env_file:
      - docker-files/databases.environ
    environment:
      - VIRTUAL_HOST={{ cookiecutter.virtual_host }}
{%- if cookiecutter.use_uwsgi_protocol == 'y' %}
      - VIRTUAL_PROTO=uwsgi
      - LETSENCRYPT_HOST={{ cookiecutter.virtual_host }}
      - LETSENCRYPT_EMAIL={{ cookiecutter.email }}
{%- endif %}
      - DJANGO_SETTINGS_MODULE={{ cookiecutter.app_name }}.settings
    volumes:
      - cmsmedia:/web/workdir
      - nginxproxy_nginxvhostd:/web/nginx-conf
    command: uwsgi --ini uwsgi.ini
    depends_on:
      - postgresdb
      - redishost
    networks:
      - cmsnet
{%- if cookiecutter.use_uwsgi_protocol == 'y' %}
      - nginx-proxy
    expose:
      - 9009
{%- else %}
    ports:
      - 9009:9009
{%- endif %}

networks:
  cmsnet:
{%- if cookiecutter.use_uwsgi_protocol == 'y' %}
  nginx-proxy:
    external: true
{%- endif %}

volumes:
  pgdata:
  redisdata:
  cmsmedia:
  esdata:
  nginxproxy_nginxvhostd:
    external: true
